export { TestappComponent } from "./testapp/testapp.component";
export { FruitproductsComponent } from "./fruitproducts/fruitproducts.component";
export { FruitbannerComponent } from "./fruitbanner/fruitbanner.component";
// export { FruitbannerboxComponent } from "./fruitbannerbox/fruitbannerbox.component";
export { FruitcestaComponent } from "./fruitcesta/fruitcesta.component";
export { FruitfooterComponent } from "./fruitfooter/fruitfooter.component";
export { FruittopbarComponent } from "./fruittopbar/fruittopbar.component";
export { TopbarComponent } from "./topbar/topbar.component";
export { FooterComponent } from "./footer/footer.component";
export { CompanyComponent } from "./company/company.component";
export { FruitcartComponent } from "./fruitcart/fruitcart.component";
export { PagoComponent } from "./pago/pago.component";
